config/routes.rb
Rails.application.routes.draw do
  get 'thanks/index'
  get 'registration/index'
  post 'registration/save_user'
  get 'driving_school/index'
  get 'clinical/index'
  get 'location/index'
  devise_for :users
  get 'home/index'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state

end

app/models/clinical.rb
class Clinical < ApplicationRecord
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :skills, :interests
  belongs_to :city
  belongs_to :location

end

app/models/driving_school.rb
class DrivingSchool < ApplicationRecord
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :skills, :interests
  belongs_to :city
  belongs_to :license

  # validates
  validates :name, :presence => true
  validates :price, :presence => true
  validates :address, :presence => true
  validates :logo, :presence => true
  validates :discount, :presence => false
end

app/models/license.rb
class License < ApplicationRecord
  
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/signature.rb
class Signature < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :city
  belongs_to :license
  belongs_to :driving_school
  belongs_to :clinical
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clinical_controller.rb
class ClinicalController < ApplicationController
  def index
    @clinical = Clinical.all
  end
end

app/controllers/driving_school_controller.rb
class DrivingSchoolController < ApplicationController
  def index
    @driving_school = DrivingSchool.all
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
  def index
    @license = params[:license]
    @long = params[:long]
    @lat = params[:lat]
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def index
    @user = User.new
    @license = License.where(name: params[:license])
    @clinical = Clinical.where(id: params[:clinical])
    @driving_school = DrivingSchool.joins(:license).where(id: params[:driving_school])
    @city = City.where(id: @driving_school[0]["city_id"])
    @state = State.where(id: @city[0]["state_id"])
  end
  def save_user
    create_user
  end

  private
    def create_user
      @user = User.new(user_params)
      if @user.save!
        redirect_to thanks_index_path( user_id: @user.id)
        flash[:notice] = "Seu usuário foi criado."
      else
        flash[:notice] = "Seu usuário não foi criado."
      end

    end
    def user_params
      params.require(:user).permit(:name, :last_name, :email, :phone, :password, :driving_school_id, :clinical_id, :license_id, :city_id)
    end

end

app/controllers/thanks_controller.rb
class ThanksController < ApplicationController

  def index
    @user = User.where(id: params[:user_id])
    @driving_school = DrivingSchool.where(id: @user[0]["driving_school_id"])
    @clinical = Clinical.where(id: @user[0]["clinical_id"])
    @city = City.where(id: @user[0]["city_id"])
    @state = State.where(id: @city[0]["state_id"] )
    @license = City.where(id: @user[0]["license_id"])

  end
  #  método export para chamar a lib que gera o PDF e depois redirecionar o usuário para baixo o PDF
 def export
   GeneratePdf::spending(User.all.map {|s| [s.section, s.value.to_f]})
   redirect_to '/spending.pdf'
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinical_helper.rb
module ClinicalHelper
end

app/helpers/driving_school_helper.rb
module DrivingSchoolHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/views/clinical/index.html.erb
<section>
    <nav class="navbar">
        <div class="container">
            <a class="navbar-brand" href="https://www.kenobi.com.br/clientes/mario/">Bolsas Autoescolas</a>
        </div>
    </nav>
    <div class="txt-apresentacao">
        <div class="container">
            <h1>Você já realizou seus Exames Clínicos e Psicotécnicos? Se ainda não, aproveite,<strong>selecione uma
                clínica e faça a sua reserva!</strong></h1>
        </div>
    </div>
    <div class="container area-clinica">
        <div class="titulo subtitulo">
            <h2>Selecione uma clínica próxima a você.</h2>
        </div>
        <% @clinical.each do |c|  %>
          <%= link_to driving_school_index_path(:license => params[:license],
            :lat => params[:lat], :long => params[:long], :clinical => c.id) do %>
            <div class="clinical">
              <div class="row">
                <div class="col-9 col-sm-10 col-md-9 col-lg-11">
                  <p><span class="nome"><%= c.name %></span></p>
                  <p><span class="endereco"><i class="fas fa-map-marker-alt"></i> CLS 402, Bloco D, Lojas 1 A 4, Asa Sul, Brasília, DF</span>
                  </p>
                  <p><span class="horario"><%= c.open %></span></p>
                  <p><span class="dias"><%= c.close %></span></p>
                  <p><span class="telefone">Telefone: <%= c.phone %></span></p>
                  <div class="tags lc">
                    <% c.tag_list.to_a.each do |t| %>
                      <span><%= t %></span>
                    <% end %>

                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>


    </div>
</section>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="logo-rdp">
                  <%= image_tag("logo2.png") %>
                </div>
                <ul class="social">
                    <li><a href=""><i class="fab fa-facebook-square"></i></a></li>
                    <li><a href=""><i class="fab fa-instagram"></i></a></li>
                    <li><a href=""><i class="fab fa-twitter-square"></i></a></li>
                    <li><a href=""><i class="fab fa-linkedin"></i></a></li>
                </ul>
            </div>
            <div class="col-md-3 lh">
                <h3>Sobre Nós</h3>
                <ul>
                    <li><a href="">Bolsas AutoEscolas</a></li>
                    <li><a href="">Como funciona</a></li>
                    <li><a href="">Blog</a></li>
                    <li><a href="">Contato</a></li>
                </ul>
            </div>
            <div class="col-md-3 lh">
                <h3>Links úteis</h3>
                <ul>
                    <li><a href="">Termo de uso</a></li>
                    <li><a href="">Política de privacidade</a></li>
                </ul>
            </div>
            <div class="col-md-3 lh">
                <h3>Acesso AutoEscolas</h3>
                <ul>
                    <li><a href="" class="btn-rdp">Acessar plataforma</a></li>
                    <li><a href="">Seja uma autoescola parceira</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

app/views/location/index.html.erb
<section>
    <nav class="navbar">
        <div class="container">
            <a class="navbar-brand" href="https://www.kenobi.com.br/clientes/mario/">Bolsas Autoescolas</a>
        </div>
    </nav>
    <div class="txt-apresentacao">
        <div class="container">
            <h1><strong>Digite seu bairro</strong> ou região de interesse!</h1>
        </div>
    </div>
    <div class="container">
        <div class="area-passos">
            <div class="row">
                <div class="col-4">
                    <div class="passos">
                       <span>1</span><p>Seleção da<br>
                       habilitação</p>
                   </div>
                </div>
                <div class="col-4">
                    <div class="passos">
                       <span>2</span><p>Seleção da<br>
                       localidade</p>
                   </div>
                </div>
                <div class="col-4">
                    <div class="passos">
                       <span>3</span><p>Seleção do<br>
                       melhor preço</p>
                   </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="area-busca">
          <div class="form-group">
              <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Digite o seu bairro ou região de interesse.">
              <div id="map"></div>
          </div>
          <div class="powered">
              <p>Powered by</p>
              <%= link_to "Avançar", clinical_index_path(:license => params[:license],
                :lat => -23.2891421, :long => -47.7096492), :class => "btn-rdp" %>
          </div>
        </div>
    </div>
</section>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="logo-rdp">
                  <%= image_tag("logo2.png") %>
                    <!-- <img src="../resource/img/logo2.png" alt="Bolsas Autoescolas"> -->
                </div>
                <ul class="social">
                    <li><a href=""><i class="fab fa-facebook-square"></i></a></li>
                    <li><a href=""><i class="fab fa-instagram"></i></a></li>
                    <li><a href=""><i class="fab fa-twitter-square"></i></a></li>
                    <li><a href=""><i class="fab fa-linkedin"></i></a></li>
                </ul>
            </div>
            <div class="col-md-3 lh">
                <h3>Sobre Nós</h3>
                <ul>
                    <li><a href="">Bolsas AutoEscolas</a></li>
                    <li><a href="">Como funciona</a></li>
                    <li><a href="">Blog</a></li>
                    <li><a href="">Contato</a></li>
                </ul>
            </div>
            <div class="col-md-3 lh">
                <h3>Links úteis</h3>
                <ul>
                    <li><a href="">Termo de uso</a></li>
                    <li><a href="">Política de privacidade</a></li>
                </ul>
            </div>
            <div class="col-md-3 lh">
                <h3>Acesso AutoEscolas</h3>
                <ul>
                    <li><a href="" class="btn-rdp">Acessar plataforma</a></li>
                    <li><a href="">Seja uma autoescola parceira</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDbeE7qXOx1Y98FS1B9k8_4LHTc21rbEyg&callback=initMap"
  type="text/javascript"></script>