config/routes.rb
Rails.application.routes.draw do
  get 'thanks/index'
  get 'registration/index'
  post 'registration/save_user'
  get 'driving_school/index'
  get 'clinical/index'
  get 'location/index'
  devise_for :users
  get 'home/index'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state

end

app/models/clinical.rb
class Clinical < ApplicationRecord
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :skills, :interests
  belongs_to :city
  belongs_to :location

end

app/models/driving_school.rb
class DrivingSchool < ApplicationRecord
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :skills, :interests
  belongs_to :city
  belongs_to :license

  # validates
  validates :name, :presence => true
  validates :price, :presence => true
  validates :address, :presence => true
  validates :logo, :presence => true
  validates :discount, :presence => false
end

app/models/license.rb
class License < ApplicationRecord
  
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/signature.rb
class Signature < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :city
  belongs_to :license
  belongs_to :driving_school
  belongs_to :clinical
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clinical_controller.rb
class ClinicalController < ApplicationController
  def index
    @clinical = Clinical.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
  def index
    @license = params[:license]
    @long = params[:long]
    @lat = params[:lat]
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def index
    @user = User.new
    @license = License.where(name: params[:license])
    @clinical = Clinical.where(id: params[:clinical])
    @driving_school = DrivingSchool.joins(:license).where(id: params[:driving_school])
    @city = City.where(id: @driving_school[0]["city_id"])
    @state = State.where(id: @city[0]["state_id"])
  end
  def save_user
    create_user
  end

  private
    def create_user
      @user = User.new(user_params)
      if @user.save!
        redirect_to thanks_index_path( user_id: @user.id)
        flash[:notice] = "Seu usuário foi criado."
      else
        flash[:notice] = "Seu usuário não foi criado."
      end

    end
    def user_params
      params.require(:user).permit(:name, :last_name, :email, :phone, :password, :driving_school_id, :clinical_id, :license_id, :city_id)
    end

end

app/controllers/thanks_controller.rb
class ThanksController < ApplicationController

  def index
    @user = User.where(id: params[:user_id])
    @driving_school = DrivingSchool.where(id: @user[0]["driving_school_id"])
    @clinical = Clinical.where(id: @user[0]["clinical_id"])
    @city = City.where(id: @user[0]["city_id"])
    @state = State.where(id: @city[0]["state_id"] )
    @license = City.where(id: @user[0]["license_id"])

  end
  #  método export para chamar a lib que gera o PDF e depois redirecionar o usuário para baixo o PDF
 def export
   GeneratePdf::spending(User.all.map {|s| [s.section, s.value.to_f]})
   redirect_to '/spending.pdf'
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinical_helper.rb
module ClinicalHelper
end

app/helpers/driving_school_helper.rb
module DrivingSchoolHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/views/home/index.html.erb
<section>
    <nav class="navbar">
        <div class="container">
            <a class="navbar-brand" href="https://www.kenobi.com.br/clientes/mario/">Bolsas Autoescolas</a>
        </div>
    </nav>
    <div class="txt-apresentacao">
        <div class="container">
            <h1>Encontre os <strong>menores preços em cursos de habilitação</strong> próximos a você!</h1>
        </div>
    </div>
    <div class="container">
        <div class="categorias">
            <div class="titulo subtitulo">
                <h2>Clique para selecionar sua habilitação de interesse.</h2>
            </div>
            <div class="area-box-categoria">
                <div class="box-categoria">
                  <%= link_to location_index_path do %>
                        <div class="tipo">
                            <p><i class="fas fa-motorcycle"></i></p>
                            <p>Primeira<br>habilitação</p>
                            <p>Moto</p>
                        </div>
                    <% end %>
                </div>
                <div class="box-categoria">
                    <%= link_to location_index_path do %>
                      <div class="tipo">
                        <p><i class="fas fa-car"></i></p>
                        <p>Primeira<br>habilitação</p>
                        <p>Carro</p>
                      </div>
                    <% end %>
                </div>
                <div class="box-categoria">
                    <%= link_to location_index_path(:license => 'AB') do %>
                        <div class="tipo">
                            <p><i class="fas fa-truck"></i></p>
                            <p>Primeira<br>habilitação</p>
                            <p>Moto + Carro</p>
                        </div>
                    <% end %>
                </div>
                <div class="box-categoria">
                    <%= link_to location_index_path(:license => 'A') do %>
                        <div class="tipo">
                          <p><i class="fas fa-bus"></i></p>
                          <p>Adicionar<br>categoria</p>
                          <p>A (moto)</p>
                        </div>
                    <% end %>
                </div>
                <div class="box-categoria">
                    <%= link_to location_index_path(:license => 'B') do %>
                        <div class="tipo">
                            <p><i class="fas fa-truck-moving"></i></p>
                            <p>Adicionar<br>categoria</p>
                            <p>B (Carro)</p>
                        </div>
                    <% end %>
                </div>
                <div class="box-categoria">
                    <%= link_to location_index_path(:license => 'C') do %>
                        <div class="tipo">
                            <p><i class="fas fa-motorcycle"></i></p>
                            <p>Adicionar<br>categoria</p>
                            <p>C (Caminhão)</p>
                        </div>
                    <% end %>
                </div>
                <div class="box-categoria">
                    <%= link_to location_index_path(:license => 'D') do %>
                        <div class="tipo">
                            <p><i class="fas fa-motorcycle"></i></p>
                            <p>Adicionar<br>categoria</p>
                            <p>D (Ônibus)</p>
                        </div>
                    <% end %>
                </div>
                <div class="box-categoria">
                    <%= link_to location_index_path(:license => 'E') do %>
                        <div class="tipo">
                            <p><i class="fas fa-motorcycle"></i></p>
                            <p>Adicionar<br>categoria</p>
                            <p>E (Carreta)</p>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="txt-info">
            <p>O Bolsas AutoEscolas é uma alternativa para você encontrar as <strong>melhores opções de preços e descontos em
                cursos de habilitação de moto e carro</strong> nas AutoEscolas mais próximas de você!</p>
        </div>
    </div>
    <div class="area-link-opcoes">
        <div class="container">
            <div class="link-opcoes">
                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md-5">
                        <div class="opcoes">
                            <span>Obter habilitação</span>
                            <ul>
                                <li><i class="fas fa-circle"></i> <a href="">Categoria A</a></li>
                                <li><i class="fas fa-circle"></i> <a href="">Categoria B</a></li>
                                <li><i class="fas fa-circle"></i> <a href="">Categoria AB</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="opcoes">
                            <span>Adicionar categoria</span>
                            <ul>
                                <li><a href=""><i class="fas fa-circle"></i> Categoria A</a></li>
                                <li><a href=""><i class="fas fa-circle"></i> Categoria B</a></li>
                                <li><a href=""><i class="fas fa-circle"></i> Categoria C</a></li>
                                <li><a href=""><i class="fas fa-circle"></i> Categoria D</a></li>
                                <li><a href=""><i class="fas fa-circle"></i> Categoria E</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-1"></div>
                </div>
            </div>
        </div>
    </div>
</section>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="logo-rdp">
                  <%= image_tag("logo2.png") %>
                    <!-- <img src="resource/img/logo2.png" alt="Bolsas Autoescolas"> -->
                </div>
                <ul class="social">
                    <li><a href=""><i class="fab fa-facebook-square"></i></a></li>
                    <li><a href=""><i class="fab fa-instagram"></i></a></li>
                    <li><a href=""><i class="fab fa-twitter-square"></i></a></li>
                    <li><a href=""><i class="fab fa-linkedin"></i></a></li>
                </ul>
            </div>
            <div class="col-md-3 lh">
                <h3>Sobre Nós</h3>
                <ul>
                    <li><a href="">Bolsas AutoEscolas</a></li>
                    <li><a href="">Como funciona</a></li>
                    <li><a href="">Blog</a></li>
                    <li><a href="">Contato</a></li>
                </ul>
            </div>
            <div class="col-md-3 lh">
                <h3>Links úteis</h3>
                <ul>
                    <li><a href="">Termo de uso</a></li>
                    <li><a href="">Política de privacidade</a></li>
                </ul>
            </div>
            <div class="col-md-3 lh">
                <h3>Acesso AutoEscolas</h3>
                <ul>
                    <li><a href="" class="btn-rdp">Acessar plataforma</a></li>
                    <li><a href="">Seja uma autoescola parceira</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

app/views/thanks/index.html.erb
<section id="printableArea">
    <nav class="navbar">
        <div class="container">
            <a class="navbar-brand" href="https://www.kenobi.com.br/clientes/mario/">Bolsas Autoescolas</a>
        </div>
    </nav>
    <div class="txt-apresentacao">
        <div class="container">
            <h1><strong>Obrigado</strong> por chegar até aqui!<br>
                Em breve uma AutoEscola parceira entrará em
                contato diretamente com você!</h1>
        </div>
    </div>
    <div class="container area-clinica">
        <div class="titulo subtitulo">
            <h2>Veja o <span>resumo</span> da sua solicitação:</h2>
        </div>
        <div class="area-resumo">
            <div class="resumo">
                <div class="row">
                    <div class="col-md-10">
                        <p class="nome-usuario"><strong>Nome: </strong><span><%= @user[0]["name"] %> <%= @user[0]["last_name"]  %></span></p>
                        <p class="email-usuario"><strong>E-mail: </strong><span><%= @user[0]["email"] %></span></p>
                        <p class="telefone-usuario"><strong>Telefone: </strong><span><%= @user[0]["phone"]  %></span></p>
                    </div>
                </div>
            </div>
            <div class="resumo">
                <div class="linha categoria">
                    <span>1ª Habilitação</span> - <span class="categoria">Categoria <%= @license[0]["name"] %></span>
                </div>
                <div class="linha convenio">
                    <span>Bolsas Autoescolas</span>
                </div>
                <div class="linha local">
                    <i class="fas fa-map-marker-alt"></i>
                    <span><%= @city[0]["name"]  %> - <%= @state[0]["name"] %></span>
                </div>
                <div class="linha incluso">
                    <h4>O que está incluso na oferta</h4>
                    <ul>
                        <li><i class="fas fa-check"></i> <span>Aulas Práticas</span></li>
                        <li><i class="fas fa-check"></i> <span>Aulas Teóricas</span></li>
                    </ul>
                </div>
                <div class="linha desconto">
                    <span>20%</span> <span>de desconto</span>
                </div>
                <div class="linha de">
                    <span>De R$</span> <span><%= @driving_school[0]["price"] %></span>
                </div>
                <div class="linha por">
                    <span>Por R$</span> <span><%= @driving_school[0]["discount"] %></span>
                </div>
                <div class="linha parcelas">
                    <span>Em até</span> <span>4x</span> <span>sem juros</span>
                </div>
            </div>
            <div class="resumo">
                <div class="row">
                    <div class="col-md-10">
                        <div class="linha">
                            <p class="nome-clinica"><span><%= @clinical[0]["name"]  %></span></p>
                        </div>
                        <div class="linha">
                            <span class="endereco"><i class="fas fa-map-marker-alt"></i> <%= @clinical[0]["address"]  %></span>

                        </div>
                        <div class="linha">
                            <span class="horario"><%= @clinical[0]["open"]  %></span>
                        </div>
                        <div class="linha">
                            <span class="dias"><%= @clinical[0]["close"]  %></span>
                        </div>
                        <div class="linha">
                            <span class="telefone">Telefone: <%= @clinical[0]["phone"]  %></span>
                        </div>
                       <div class="tags lc">
                         <% @clinical[0].tag_list.to_a.each do |t| %>
                            <span><%= t %></span>
                          <% end %>
                        </div>
                        <div class="linha">
                            <p class="obs">OBS: Encaminhar-se a clínica dentro dos horários de funcionamento indicados.</p>
                        </div>
                    </div>
                </div>
            </div>
            <input type="button" class="btn" onclick="printDiv('printableArea')" value="Imprimir resumo" />
            <button type="button" class="btn btn-blog">Conhecer o Blog</button>
        </div>
    </div>
</section>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="logo-rdp">
                  <%= image_tag("logo2") %>
                    <!-- <img src="../resource/img/logo2.png" alt="Bolsas Autoescolas"> -->
                </div>
                <ul class="social">
                    <li><a href=""><i class="fab fa-facebook-square"></i></a></li>
                    <li><a href=""><i class="fab fa-instagram"></i></a></li>
                    <li><a href=""><i class="fab fa-twitter-square"></i></a></li>
                    <li><a href=""><i class="fab fa-linkedin"></i></a></li>
                </ul>
            </div>
            <div class="col-md-3 lh">
                <h3>Sobre Nós</h3>
                <ul>
                    <li><a href="">Bolsas AutoEscolas</a></li>
                    <li><a href="">Como funciona</a></li>
                    <li><a href="">Blog</a></li>
                    <li><a href="">Contato</a></li>
                </ul>
            </div>
            <div class="col-md-3 lh">
                <h3>Links úteis</h3>
                <ul>
                    <li><a href="">Termo de uso</a></li>
                    <li><a href="">Política de privacidade</a></li>
                </ul>
            </div>
            <div class="col-md-3 lh">
                <h3>Acesso AutoEscolas</h3>
                <ul>
                    <li><a href="" class="btn-rdp">Acessar plataforma</a></li>
                    <li><a href="">Seja uma autoescola parceira</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>